project:
  type: book
  output-dir: _book

book:
  title: "Esteios"
  subtitle: "Notas para a minha filha"
  author: "bmhash"
  date: today
  date-format: "D MMMM YYYY"
  language: pt

  chapters:
    - index.qmd

format:
  html:
    theme: 
      - litera
      - styles/typography.scss
    css: styles/landing.css
    toc: false
    number-sections: false
    lang: pt
    link-external-newwindow: true
    page-navigation: false
