project:
  type: website
  output-dir: _site

website:
  title: "Esteios"

format:
  html:
    theme: none
    css: styles/minimal.css
    toc: false
    number-sections: false
    lang: pt
    minimal: true
    page-layout: custom
